#!/bin/bash

event_type=$1
event_name=$2
event_description=$3

exec 100>/var/tmp/testlock.lock || exit 1
flock 100 || exit 1

logger -t status "$1 -- $2"
if [[ -n "$3" ]]; then
    logger -t status "    $3"
fi
